export const appwriteConfig = {
    platform: "com.phanie.fooddelivery",
    endpoint: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,
    projectId: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!,
    databaseId: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID!,
    bucketId: process.env.EXPO_PUBLIC_APPWRITE_ASSETS_ID!,
    userCollectionId: process.env.EXPO_PUBLIC_APPWRITE_USER_ID!,
    categoryCollectionId: process.env.EXPO_PUBLIC_APPWRITE_CATEGORY_ID!,
    menuCollectionId: process.env.EXPO_PUBLIC_APPWRITE_MENU_ID!,
    customizationsCollectionId: process.env.EXPO_PUBLIC_APPWRITE_CUSTOMIZATIONS_ID!,
    menu_customizationsCollectionId: process.env.EXPO_PUBLIC_APPWRITE_MENU_CUSTOMIZATIONS_ID!,
    offersCollectionId: process.env.EXPO_PUBLIC_APPWRITE_OFFERS_ID!,
    reviewsCollectionId: process.env.EXPO_PUBLIC_APPWRITE_REVIEWS_ID!,
    cartCollectionId: process.env.EXPO_PUBLIC_APPWRITE_CART_ID!,
    customizationsBoardsCollectionId: process.env.EXPO_PUBLIC_APPWRITE_CUSTOMIZATIONS_BOARD_ID,
    restaurantCollectionId: process.env.EXPO_PUBLIC_APPWRITE_RESTAURANT_ID!,
};
